"""Crear tablas iniciales

Revision ID: 1238707ec9c3
Revises: 
Create Date: 2025-08-13 13:43:13.222937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1238707ec9c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediciones_corporales', sa.Column('altura', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('imc', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('cuello', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('hombros', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('brazo_der_relajado', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('brazo_izq_relajado', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('brazo_der_flexionado', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('brazo_izq_flexionado', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('antebrazo_der', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('mediciones_corporales', sa.Column('antebrazo_izq', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediciones_corporales', 'antebrazo_izq')
    op.drop_column('mediciones_corporales', 'antebrazo_der')
    op.drop_column('mediciones_corporales', 'brazo_izq_flexionado')
    op.drop_column('mediciones_corporales', 'brazo_der_flexionado')
    op.drop_column('mediciones_corporales', 'brazo_izq_relajado')
    op.drop_column('mediciones_corporales', 'brazo_der_relajado')
    op.drop_column('mediciones_corporales', 'hombros')
    op.drop_column('mediciones_corporales', 'cuello')
    op.drop_column('mediciones_corporales', 'imc')
    op.drop_column('mediciones_corporales', 'altura')
    # ### end Alembic commands ###
